import Card from '../components/Card';
import SilhouetteGauge from '../components/SilhouetteGauge';
import LoadingSkeleton from '../components/LoadingSkeleton';
import ErrorBanner from '../components/ErrorBanner';
import EmptyState from '../components/EmptyState';
import useClustering from '../hooks/useClustering';

export default function Dendrogram() {
  const { clustering, dendrogram, imageSrc, loading, error, hasData } = useClustering();

  if (loading) return <LoadingSkeleton />;
  if (error) return <ErrorBanner message={error} />;
  if (!hasData) return <EmptyState description="No dendrogram available yet. Upload a dataset to generate a hierarchical clustering tree visualization." linkText="Upload Dataset" />;

  const clusters = clustering?.clusters ?? [];
  const silhouette = clustering?.silhouette ?? 0;

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h2 className="text-xl font-bold text-slate-800">Dendrogram</h2>
        <p className="text-sm text-slate-400 mt-0.5">
          Hierarchical clustering tree — visualizing step-by-step customer group merges
        </p>
      </div>

      {/* Summary cards */}
      <div className="grid grid-cols-2 sm:grid-cols-5 gap-4">
        <Card className="px-5 py-4 text-center">
          <p className="text-xl font-bold text-slate-800">{clusters.length}</p>
          <p className="text-xs text-slate-400 mt-1">Clusters</p>
        </Card>
        <Card className="px-5 py-4 text-center">
          <p className="text-xl font-bold text-slate-800">Ward</p>
          <p className="text-xs text-slate-400 mt-1">Linkage</p>
        </Card>
        <Card className="px-5 py-4 text-center">
          <p className="text-xl font-bold text-slate-800">Euclidean</p>
          <p className="text-xs text-slate-400 mt-1">Distance</p>
        </Card>
        <Card className="px-5 py-4 text-center">
          <p className="text-xl font-bold text-slate-800">{dendrogram?.n_obs ?? '-'}</p>
          <p className="text-xs text-slate-400 mt-1">Observations</p>
        </Card>
        <Card className="px-5 py-4 flex flex-col items-center">
          <SilhouetteGauge score={silhouette} size={72} />
          <p className="text-[10px] text-slate-400 mt-1">Silhouette</p>
        </Card>
      </div>

      {/* Dendrogram image generated by scipy + matplotlib */}
      <Card title="Cluster Dendrogram" description="Ward linkage — merges minimizing within-cluster variance">
        <div className="flex justify-center py-3 px-4">
          {imageSrc ? (
            <img
              src={imageSrc}
              alt="Hierarchical Clustering Dendrogram"
              className="max-w-full h-auto rounded-lg"
              style={{ maxWidth: '1080px', width: '100%' }}
            />
          ) : (
            <p className="text-sm text-slate-400 py-8">Loading dendrogram...</p>
          )}
        </div>
      </Card>

      {/* How to read */}
      <Card title="How to Read This Chart">
        <div className="px-5 pb-5">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <h4 className="text-sm font-bold text-slate-700 mb-2">Merge Height</h4>
              <ul className="space-y-2 text-sm text-slate-500 leading-relaxed">
                <li className="flex items-start gap-2">
                  <span className="text-emerald-500 font-bold mt-0.5">●</span>
                  <span><strong className="text-slate-600">Low merge height</strong> = customers are very similar. They form tight, coherent groups.</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-amber-500 font-bold mt-0.5">●</span>
                  <span><strong className="text-slate-600">High merge height</strong> = groups are very different. Merging them increases variance significantly.</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-red-400 font-bold mt-0.5">
                    <span className="inline-block w-4 h-0 border-t border-red-400 border-dashed" />
                  </span>
                  <span><strong className="text-slate-600">Red dashed line</strong> = the cut threshold. Everything below this line forms one of the 4 final clusters.</span>
                </li>
              </ul>
            </div>
            <div>
              <h4 className="text-sm font-bold text-slate-700 mb-2">Color Groups</h4>
              <p className="text-sm text-slate-500 leading-relaxed mb-3">
                Branches sharing the same color belong to the same cluster when the tree is cut at 4 groups. The further apart
                two branches split, the less similar those customer groups are.
              </p>
              <p className="text-sm text-slate-500 leading-relaxed">
                This dendrogram uses <span className="font-medium text-slate-600">{dendrogram?.n_obs ?? 300}</span> randomly sampled
                customers (seeded for reproducibility) from <span className="font-medium text-slate-600">{(clustering?.labels?.length ?? 5000).toLocaleString()}</span> total.
              </p>
            </div>
          </div>
        </div>
      </Card>

      {/* Cluster legend */}
      <Card title="Cluster Legend">
        <div className="flex items-center gap-4 flex-wrap px-5 pb-5">
          {clusters.map((c) => (
            <div key={c.id} className="flex items-center gap-2 bg-slate-50 rounded-lg px-3 py-2">
              <div className="w-3 h-3 rounded-full" style={{ backgroundColor: c.color }} />
              <span className="text-xs font-medium text-slate-600">{c.name}</span>
              <span className="text-[10px] text-slate-400">({c.size} customers)</span>
            </div>
          ))}
        </div>
      </Card>
    </div>
  );
}
